### ISSUE TITLE
Monte Carlo, expected value, and hypergeometric discrete RV

### ISSUE THREAD

**Issue by agzimmerman** [nalkpas/hand-simulator#1]
Cool project. I found this through [Alex Majlaton's article on CFB](https://www.channelfireball.com/articles/a-new-affinity-for-2018-top-16-at-grand-prix-phoenix/).

So I was having some trouble looking through the source and figuring out where the Monte Carlo method is used. But now I see that you're using this hypergeometric discrete random variable (RV) from SciPy. So I would think that the Monte Carlo method would require you to sample realizations of the RV and use the law of large numbers to estimate the mean. But I see that you simply call `hypergeom.mean`. Looking through the [SciPy hypergeom source code](https://github.com/scipy/scipy/blob/v1.0.0/scipy/stats/_discrete_distns.py), I am not easily understanding where they compute the mean. If you are interested in taking the time, could you maybe explain how you get from this RV to the results you talk about in [your blog post](http://wiresandstarlings.tumblr.com/post/171334677044/when-i-get-to-california-im-gonna-write-my-name)?

Thanks!

P.S. I tend to use issues to document all sorts of things like this, not just bugs in my code. My apologies if you wanted to keep your issues empty. Let me know if there's a better way to communicate :)

P.P.S. I hadn't ever seen this hypergeomtric discrete RV. I had put a bit of thought into how I might want to do a project like this a while back, but never actually implemented anything (though I've used Monte Carlo for some engineering stuff). This looks like a really useful part of SciPy that I'll be keeping in mind.

**Comment by agzimmerman** [comment]
Looking through some of the applications, e.g. *affinity.py*, it is pretty clear (to me) that here the Monte Carlo integration is just written by hand with a for loop, and there's a parameter for how many realizations you want (i.e. the sample size). So I think I could probably take the time to read the code line by line and figure out exactly how you get to your results in the blog post. 

Maybe when I want to do some weekend coding I'll try forking this and encapsulating the Monte Carlo method, unless you were planning to do that anyway.

**Comment by nalkpas** [comment]
Sorry, I don't usually check GitHub. You can message me on Twitter (@nalkpas) or on Facebook. But yeah, the MCS is primarily in the files directly pertaining to particular decks. hand_simulator.py is just a helper class to make the MCS easier.
